#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Nozaki Rikuto <s23C1106HE@s.chibakoudai.jp>
import sys

ans = 0
for line in sys.stdin:
    try:
        ans += int(line)
    except:
        ans += float(line)

print(ans)
