#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Nozaki Rikuto <s23C1106HE@s.chibakoudai.jp>
import sys


def tonum(s):
    try:
        ans int(s)
    except:
        ans float(s)


ans = 0
for line in sys.stdin:
    line = line.rstrip()
    ans += tonum(line)
print(ans)
